### ISSUE TITLE
Console error (I can't open console)

### ISSUE THREAD

**Issue by Wobbledongle101** [Lyall/WukongTweak#8] opened 2024-08-25 09:48 UTC
[WukongTweak] [error] Construct Console: Failed to find GEngine address after 10 seconds. In the wukongtweaklog

also do I edit the 'consolekeys=tilde' to whatever key I want?

I can't open console

**Comment by Deenharin** [comment] 2024-08-25 11:01
yeah me to cant open console, how to fix it?
![Error](https://github.com/user-attachments/assets/dfa6f191-24e0-4711-bd17-280645ab613d)

**Comment by Lyall** [comment] 2024-08-25 13:16
Can you try this test build? It attempts to search for GEngine for 30 seconds instead of 10.

[WukongTweak_v0.8.2_test.zip](https://github.com/user-attachments/files/16740376/WukongTweak_v0.8.2_test.zip)

**Comment by Wobbledongle101** [comment] 2024-08-25 13:30
That worked

**Comment by Wobbledongle101** [comment] 2024-08-25 13:39
https://github.com/user-attachments/assets/5d7bb437-f0f8-48e4-aba1-00c1cf97211a

There is this weird dark filter that moves when my camera moves all around the edges of my screen. do you know what's causing this?

**Comment by Deenharin** [comment] 2024-08-25 14:33
> That worked

did you change the key? because I use the default key but it still doesn't work

**Comment by Wobbledongle101** [comment] 2024-08-25 14:46
> > That worked
> 
> did you change the key? because I use the default key but it still doesn't work

No, I didn't change the key, its still 'Tilde'.

**Comment by Deenharin** [comment] 2024-08-25 14:58
> > > That worked
> > 
> > 
> > did you change the key? because I use the default key but it still doesn't work
> 
> No, I didn't change the key, its still 'Tilde'.

can you try taking a photo in the input.ini settings for me?

**Comment by Wobbledongle101** [comment] 2024-08-25 15:01
> > > > That worked
> > > 
> > > 
> > > did you change the key? because I use the default key but it still doesn't work
> > 
> > 
> > No, I didn't change the key, its still 'Tilde'.
> 
> can you try taking a photo in the input.ini settings for me?

![image](https://github.com/user-attachments/assets/e58924f7-7be3-4888-801e-38bdf0422bb5)

**Comment by Deenharin** [comment] 2024-08-25 15:10
> > > > > That worked
> > > > 
> > > > 
> > > > did you change the key? because I use the default key but it still doesn't work
> > > 
> > > 
> > > No, I didn't change the key, its still 'Tilde'.
> > 
> > 
> > can you try taking a photo in the input.ini settings for me?
> 
> ![image](https://private-user-images.githubusercontent.com/179376953/361240474-e58924f7-7be3-4888-801e-38bdf0422bb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTgzODIsIm5iZiI6MTcyNDU5ODA4MiwicGF0aCI6Ii8xNzkzNzY5NTMvMzYxMjQwNDc0LWU1ODkyNGY3LTdiZTMtNDg4OC04MDFlLTM4YmRmMDQyMmJiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNVQxNTAxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDc5MjU2NzQ1NjlmMTYyYjM0NDEzNjgxYTZkY2RlMzAzYzg0OTA2YzQxNThiMDJkYTQzYTcxYTBiYjM0NzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FYkD9v1iPPIFb_QqPIZUg_JxuD5OXZEmz1m7Q2dZYhE)

okay thanks

**Comment by Lyall** [comment] 2024-08-25 15:15
> weird.mp4 
> (zoomed in on a corner) There is this weird dark filter that moves when my camera moves all around the edges of my screen. do you know what's causing this?

Not exactly sure what that is. It kind of looks like a frame-generation artifact. Are you using frame generation?

**Comment by Wobbledongle101** [comment] 2024-08-25 15:25
> > weird.mp4
> > (zoomed in on a corner) There is this weird dark filter that moves when my camera moves all around the edges of my screen. do you know what's causing this?
> 
> Not exactly sure what that is. It kind of looks like a frame-generation artifact. Are you using frame generation?

Ah yes it is due to frame generation tried turning it off and on.  Is there a way to fix it without turning frame generation off? I also use the dlssg-to-fsr3 mod.

**Comment by Lyall** [comment] 2024-08-25 15:32
> > > weird.mp4
> > > (zoomed in on a corner) There is this weird dark filter that moves when my camera moves all around the edges of my screen. do you know what's causing this?
> > 
> > 
> > Not exactly sure what that is. It kind of looks like a frame-generation artifact. Are you using frame generation?
> 
> Ah yes it is due to frame generation tried turning it off and on. Is there a way to fix it without turning frame generation off? I also use the dlssg-to-fsr3 mod.

Not really that I know of. These kind of things are to be expected when modding like this. You could try disabling the vignette maybe? It kind of looks like an overlay is interpreted as having motion vectors by the dlssg->fsr mod.

**Comment by wendrahartanto** [comment] 2024-08-26 09:19
> weird.mp4 
> (zoomed in on a corner) There is this weird dark filter that moves when my camera moves all around the edges of my screen. do you know what's causing this?

got the same problem here

**Comment by K-Anudeep** [comment] 2024-08-26 10:52
> Can you try this test build? It attempts to search for GEngine for 30 seconds instead of 10.
> 
> [WukongTweak_v0.8.2_test.zip](https://github.com/user-attachments/files/16740376/WukongTweak_v0.8.2_test.zip)

This has worked for me too, thanks for your continued help!

**Comment by Lyall** [comment] 2024-08-26 12:21
> > weird.mp4
> > (zoomed in on a corner) There is this weird dark filter that moves when my camera moves all around the edges of my screen. do you know what's causing this?
> 
> got the same problem here

You can refer to my other comment about this. It isn't caused by WukongTweak and I don't know for sure how to fix it other than not using the FSR frame generation mod.

**Comment by klofi** [comment] 2024-08-27 21:11
@Lyall Related to console, the instructions on how to enable the key is only present in https://github.com/Lyall/WukongTweak/releases/tag/v0.8.2, can you add it to https://github.com/Lyall/WukongTweak/blob/master/README.md#installation ? Cheers.

**Comment by Lyall** [comment] 2024-08-27 23:28
> @Lyall Related to console, the instructions on how to enable the key is only present in https://github.com/Lyall/WukongTweak/releases/tag/v0.8.2, can you add it to https://github.com/Lyall/WukongTweak/blob/master/README.md#installation ? Cheers.

Added.

Console timeout issue should be fixed in v0.8.3

**Closed by Lyall** 2024-08-27 23:28 UTC
